//
//  MockRecording.swift
//  LeapSwift
//

import Foundation

/// A recorded sequence of ``HandFrame`` values for one ``MockScenario``.
///
/// Recordings are plain JSON — one file per scenario is generated by
/// ``generate(scenario:duration:frameRate:)`` and committed to the framework's
/// bundle, but you can also record and ``write(to:)`` your own, or hand-author
/// one, and ``load(contentsOf:)`` it back. Both use the same file format.
public struct MockRecording: Codable, Sendable {
    /// The scenario name this recording was generated from.
    public let name: String
    /// The frame rate the recording was captured at.
    public let frameRate: Float
    /// The recorded frames, in order.
    public let frames: [HandFrame]

    /// Creates a recording directly. Prefer ``generate(scenario:duration:frameRate:)``
    /// unless you are assembling frames from another source.
    public init(name: String, frameRate: Float, frames: [HandFrame]) {
        self.name = name
        self.frameRate = frameRate
        self.frames = frames
    }

    /// Procedurally generates a recording of `scenario`.
    ///
    /// This is exactly how the JSON files bundled with LeapSwift are built —
    /// see `MockRecordingDriftTests` for the test that keeps them in sync with
    /// this function.
    ///
    /// - Parameters:
    ///   - scenario: The scenario to animate.
    ///   - duration: How long the recording should be, in seconds.
    ///   - frameRate: The frame rate to generate at.
    /// - Returns: A recording with `duration * frameRate` frames, frame ids
    ///   starting at `0`.
    public static func generate(scenario: MockScenario, duration: TimeInterval, frameRate: Float) -> MockRecording {
        let frameCount = Int((duration * Double(frameRate)).rounded())
        let frames = (0..<frameCount).map { i in
            MockHandFactory.frame(scenario: scenario, frameId: Int64(i), time: TimeInterval(i) / Double(frameRate), frameRate: frameRate)
        }
        return MockRecording(name: scenario.rawValue, frameRate: frameRate, frames: frames)
    }

    /// Loads the recording bundled with LeapSwift for `scenario`.
    ///
    /// - Throws: ``MockRecordingError/resourceNotFound(_:)`` if the framework
    ///   was built without the bundled `MockData`, or any error `load(contentsOf:)`
    ///   can throw.
    public static func bundled(_ scenario: MockScenario) throws -> MockRecording {
        guard let url = Bundle.leapSwiftResources.url(forResource: scenario.rawValue, withExtension: "json") else {
            throw MockRecordingError.resourceNotFound(scenario)
        }
        return try load(contentsOf: url)
    }

    /// Loads a recording from a JSON file, in the same format ``write(to:)``
    /// produces.
    ///
    /// - Parameter url: The file to read.
    /// - Throws: An error if the file can't be read or doesn't decode as a
    ///   recording.
    public static func load(contentsOf url: URL) throws -> MockRecording {
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(MockRecording.self, from: data)
    }

    /// Writes the recording to `url` as unformatted JSON.
    ///
    /// - Parameter url: The file to write. Overwrites any existing file.
    /// - Throws: An error if encoding or writing fails.
    public func write(to url: URL) throws {
        let data = try Self.encoder.encode(self)
        try data.write(to: url)
    }

    // `JSONEncoder`'s default keyed container ordering is not stable across
    // process launches (it's backed by a Dictionary, whose iteration order
    // depends on a per-process hash seed), so two encodes of the same value
    // in two different `swift test` invocations can produce byte-for-byte
    // different — but equally valid — JSON. `.sortedKeys` fixes the order, so
    // the file `write(to:)` produces is reproducible and diffs cleanly, and
    // `MockRecordingDriftTests` can compare encoded bytes directly.
    static let encoder: JSONEncoder = {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.sortedKeys]
        return encoder
    }()
}

/// Errors thrown by ``MockRecording``.
public enum MockRecordingError: Error, LocalizedError, Sendable {
    /// ``MockRecording/bundled(_:)`` could not find `scenario`'s JSON file in
    /// the framework's resource bundle.
    case resourceNotFound(MockScenario)

    public var errorDescription: String? {
        switch self {
        case .resourceNotFound(let scenario):
            return "No bundled mock recording found for scenario \"\(scenario.rawValue)\""
        }
    }
}
